### ISSUE TITLE
Window controls are not visible

### ISSUE THREAD

**Issue by Rezrazi** [Eugeny/terminus-theme-hype#2]
Screenshot says it all
![terminus](https://user-images.githubusercontent.com/2086576/28110699-1a18ef7a-66eb-11e7-8d9e-4756cc7e7494.png)

**OS** Windows 10 15063
**Terminus** 1.0 Alpha 20

**Comment by ShekhSaifuddin007** [comment]
What was the process to get hype..?? I want this but I'm failed.. @Rezrazi
